export default {
  // 品牌管理
  BRAND_GET: '/api/pdos/base/brand/get',
  BRAND_CHECKCODE: '/api/pdos/base/brand/checkUnique',
  BRAND_LIST: '/api/pdos/base/brand/list',
  BRAND_EDIT: '/api/pdos/base/brand/edit',
  BRAND_DEL: '/api/pdos/base/brand/del',
  // 供应商管理
  SUPPLIER_GET: '/api/pdos/base/supplier/get',
  SUPPLIER_CHECKCODE: '/api/pdos/base/supplier/checkUnique',
  SUPPLIER_LIST: '/api/pdos/base/supplier/list',
  SUPPLIER_EDIT: '/api/pdos/base/supplier/edit',
  SUPPLIER_DEL: '/api/pdos/base/supplier/del',
  // 分类管理
  CATEGORY_GET: '/api/pdos/base/category/get',
  CATEGORY_LIST: '/api/pdos/base/category/list',
  CATEGORY_EDIT: '/api/pdos/base/category/edit',
  CATEGORY_DEL: '/api/pdos/base/category/del',
  CATEGORY_SORT: '/api/pdos/base/category/sort',
  CATEGORY_STATUS: '/api/pdos/base/category/switchStatus',
  CATEGORY_CHECKUNIQUE: '/api/pdos/base/category/checkUnique',
  // 店铺管理
  SHOP_GET: '/api/pdos/base/shop/get',
  SHOP_CHECKUNIQUE: '/api/pdos/base/shop/checkUnique',
  SHOP_LIST: '/api/pdos/base/shop/list',
  SHOP_EDIT: '/api/pdos/base/shop/edit',
  SHOP_DEL: '/api/pdos/base/shop/del',
  // 订单管理
  ORDER_GET: '/api/pdos/sale/orders/get',
  ORDER_CHECKCODE: '/api/pdos/sale/orders/checkUnique',
  ORDER_LIST: '/api/pdos/sale/orders/list',
  ORDER_EDIT: '/api/pdos/sale/orders/edit',
  ORDER_DEL: '/api/pdos/sale/orders/del',
  //商品管理
  GOODS_GET: '/api/pdos/sale/goods/get',
  GOODS_CHECKCODE: '/api/pdos/sale/goods/checkUnique',
  GOODS_LIST: '/api/pdos/sale/goods/list',
  GOODS_LISTALL: '/api/pdos/sale/goods/listAll',
  GOODS_EDIT: '/api/pdos/sale/goods/edit',
  GOODS_DEL: '/api/pdos/sale/goods/del',
}
