export default {
  /**  系统管理 * */
  // 部门管理
  ORG_GET: '/api/sys/organization/get',
  ORG_LIST: '/api/sys/organization/list',
  ORG_EDIT: '/api/sys/organization/edit',
  ORG_DEL: '/api/sys/organization/del',
  ORG_SORT: '/api/sys/organization/sort',
  ORG_STATUS: '/api/sys/organization/switchStatus',
  ORG_CHECKUNIQUE: '/api/sys/organization/checkUnique',
  // 模块管理
  MODULE_GET: '/api/sys/module/get',
  MODULE_LIST: '/api/sys/module/listNoPage',
  MODULE_EDIT: '/api/sys/module/edit',
  MODULE_SORT: '/api/sys/module/sort',
  MODULE_DEL: '/api/sys/module/del',
  MODULE_STATUS: '/api/sys/module/switchStatus',
  MODULE_CHECKUNIQUE: '/api/sys/module/checkUnique',
  // 字典管理
  DICT_GET: '/api/sys/dictionary/get',
  DICT_LIST: '/api/sys/dictionary/list',
  DICT_EDIT: '/api/sys/dictionary/edit',
  DICT_DEL: '/api/sys/dictionary/del',
  // 角色管理
  ROLE_GET: '/api/sys/role/get',
  ROLE_LIST: '/api/sys/role/list',
  ROLE_DEL: '/api/sys/role/del',
  ROLE_SAVE: '/api/sys/role/save',
  ROLE_LOCK: '/api/sys/role/lock',
  ROLE_SAVEUSER: '/api/sys/role/saveUser',
  ROLE_SAVEMODULE: '/api/sys/role/saveModule',
  ROLE_CHECKUNIQUE: '/api/sys/role/checkUnique',
  ROLE_LISTMOUDLE: '/api/sys/role/listModule',
  ROLE_LISTUSER: '/api/sys/role/listUser',
  // 用户管理
  ACCOUNT_GET: '/api/sys/account/get',
  ACCOUNT_LIST: '/api/sys/account/list',
  ACCOUNT_CHECKUNIQUE: '/api/sys/account/checkUnique',
  ACCOUNT_EDIT: '/api/sys/account/edit',
  ACCOUNT_GRANT: '/api/sys/account/grant',
  ACCOUNT_DEL: '/api/sys/account/del',
  ACCOUNT_LOCK: '/api/sys/account/lock',
  // 品牌管理
  BRAND_GET: '/api/pdos/base/brand/get',
  BRAND_LIST: '/api/pdos/base/brand/list',
  BRAND_EDIT: '/api/pdos/base/brand/edit',
  BRAND_DEL: '/api/pdos/base/brand/del',
  // 供应商管理
  SUPPLIER_GET: '/api/pdos/base/supplier/get',
  SUPPLIER_LIST: '/api/pdos/base/supplier/list',
  SUPPLIER_EDIT: '/api/pdos/base/supplier/edit',
  SUPPLIER_DEL: '/api/pdos/base/supplier/del',
  // 分类管理
  CATEGORY_GET: '/api/pdos/base/category/get',
  CATEGORY_LIST: '/api/pdos/base/category/list',
  CATEGORY_EDIT: '/api/pdos/base/category/edit',
  CATEGORY_DEL: '/api/pdos/base/category/del',
  CATEGORY_SORT: '/api/pdos/base/category/sort',
  CATEGORY_STATUS: '/api/pdos/base/category/switchStatus',
  CATEGORY_CHECKUNIQUE: '/api/pdos/base/category/checkUnique',
  // 店铺管理
  SHOP_GET: '/api/pdos/base/shop/get',
  SHOP_LIST: '/api/pdos/base/shop/list',
  SHOP_EDIT: '/api/pdos/base/shop/edit',
  SHOP_DEL: '/api/pdos/base/shop/del',

  // 订单管理
  ORDER_GET: '/api/pdos/sale/orders/get',
  ORDER_LIST: '/api/pdos/sale/orders/list',
  ORDER_EDIT: '/api/pdos/sale/orders/edit',
  ORDER_DEL: '/api/pdos/sale/orders/del',

  /**  系统日志 * */
  // 在线用户
  ONLINE_LIST: '/api/monitor/log/online/list',
  // 错误日志
  ERROR_GET: '/api/monitor/log/error/get',
  ERROR_LIST: '/api/monitor/log/error/list',
  // 业务日志
  BIZLOG_GET: '/api/monitor/log/biz/get',
  BIZLOG_LIST: '/api/monitor/log/biz/list',
}
